### ISSUE TITLE
About command not working

### ISSUE THREAD

**Issue by skranz0** [skatkov/stoic#28]
Trying `stoic --about` after installing with brew only gives
```bash
$ stoic --about
Version: 
Build Hash: 
```
without any real information.

**Comment by skatkov** [comment]
Thanks!

Yeah, this is a known issue, I wanted to migrate to goreleaser that would populate these values. 

My current Makefile approach of building this doesn't work as flawlessly :)

**Comment by skranz0** [comment]
No worries, but if it's a known issues, it's good to have it written down in the ... well ... _issues_

**Comment by skatkov** [comment]
Indeed. Thanks for raising this.

**Comment by skatkov** [comment]
Should be working at all times now with 0.6.1 release.
